/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SwDev06
 */
public class CalculatorApplet extends java.applet.Applet {
//VARIABLES FOR THE PROGRAM

    String strNum1;
    String strNum2;

    int intResult;
    int intnum1;
    int intnum2;

    boolean Divide, Multiply, Subtract, Add;

    /**
     * Initializes the applet CalculatorApplet
     */
    public void init() {
        resize(350, 370);
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    //METHODS FOR CALCULATIONS
    //Division
    public int Division() {
        intResult = intnum1 / intnum2;
        return intResult;
    }

    //Multiplied
    public int Multiply() {
        intResult = intnum1 * intnum2;
        return intResult;
    }

    //Subtract
    public int Subtract() {
        intResult = intnum1 - intnum2;
        return intResult;
    }

    //Add
    public int Add() {
        intResult = intnum1 + intnum2;
        return intResult;
    }
    //THE END OF THE METHODS FOR CALCULATIONS

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCalculator = new javax.swing.JLabel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblResultLabel = new java.awt.Label();
        btn0 = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnDevide = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCalculator.setText("Calculator");
        add(lblCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 30, 114, -1));

        btn7.setBackground(new java.awt.Color(204, 204, 204));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 137, 42, 44));

        btn8.setBackground(new java.awt.Color(204, 204, 204));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 137, 42, 44));

        btn9.setBackground(new java.awt.Color(204, 204, 204));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 137, 42, 44));

        btn6.setBackground(new java.awt.Color(204, 204, 204));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 187, 42, 44));

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 187, 42, 44));

        btn5.setBackground(new java.awt.Color(204, 204, 204));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 187, 42, 44));

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 237, 42, 44));

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 237, 42, 44));

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 237, 42, 44));

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setText("Clear");
        btnClear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnClearFocusLost(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 299, -1, -1));

        lblResultLabel.setAlignment(java.awt.Label.RIGHT);
        lblResultLabel.setBackground(java.awt.Color.white);
        add(lblResultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 75, 138, 28));

        btn0.setBackground(new java.awt.Color(204, 204, 204));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 299, 89, -1));

        btnSubtract.setBackground(new java.awt.Color(204, 204, 204));
        btnSubtract.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSubtract.setText("-");
        btnSubtract.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSubtractFocusLost(evt);
            }
        });
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        add(btnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 171, 57, -1));

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnAddFocusLost(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 223, 57, -1));

        btnEquals.setBackground(new java.awt.Color(204, 204, 204));
        btnEquals.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        add(btnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 275, 57, -1));

        btnDevide.setBackground(new java.awt.Color(204, 204, 204));
        btnDevide.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDevide.setText("/");
        btnDevide.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnDevideFocusLost(evt);
            }
        });
        btnDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevideActionPerformed(evt);
            }
        });
        add(btnDevide, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 67, 57, -1));

        btnMultiply.setBackground(new java.awt.Color(204, 204, 204));
        btnMultiply.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnMultiplyFocusLost(evt);
            }
        });
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 119, 57, -1));
    }// </editor-fold>//GEN-END:initComponents

    //NUMERIC VALUE BUTTONS
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        lblResultLabel.setText("0");

    }//GEN-LAST:event_btnClearActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        lblResultLabel.setText(lblResultLabel.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed


    private void btnClearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClearFocusLost
        lblResultLabel.setText("");
        Divide = false;
        Multiply = false;
        Subtract = false;
        Add = false;
    }//GEN-LAST:event_btnClearFocusLost

    private void btnDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevideActionPerformed
        //BUTTON DIVISION
        Divide = true;
        strNum1 = lblResultLabel.getText();

    }//GEN-LAST:event_btnDevideActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        //BUTTON MULTIPLICATION
        Multiply = true;
        strNum1 = lblResultLabel.getText();
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        //BUTTON SUBRACTION
        Subtract = true;
        strNum1 = lblResultLabel.getText();
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //BUTTON ADDITION
        Add = true;
        strNum1 = lblResultLabel.getText();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        //THIS IS THE EQUALS BUTTON AND THE CONVERSIONS HAPPEN HERE
        strNum2 = lblResultLabel.getText();
        intnum1 = Integer.parseInt(strNum1);
        intnum2 = Integer.parseInt(strNum2);

        //DECISION MAKING FOR THE EQUALS BUTTON, DEPENDING ON WHICH CALCULATION IS CLICKED
        if (Divide == true) { //if Divide button is pressed before equals
            lblResultLabel.setText(String.valueOf(Division()));
        } else if (Multiply == true) { //if Multiply button is pressed before equals
            lblResultLabel.setText(String.valueOf(Multiply()));
        } else if (Subtract == true) { //if Subtract button is pressed before equals
            lblResultLabel.setText(String.valueOf(Subtract()));
        } else if (Add == true) { //if Add button is pressed before equals
            lblResultLabel.setText(String.valueOf(Add()));
        }

    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnDevideFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDevideFocusLost
        lblResultLabel.setText("");
    }//GEN-LAST:event_btnDevideFocusLost

    private void btnMultiplyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnMultiplyFocusLost
        lblResultLabel.setText("");
    }//GEN-LAST:event_btnMultiplyFocusLost

    private void btnSubtractFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSubtractFocusLost
        lblResultLabel.setText("");
    }//GEN-LAST:event_btnSubtractFocusLost

    private void btnAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAddFocusLost
        lblResultLabel.setText("");
    }//GEN-LAST:event_btnAddFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDevide;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JLabel lblCalculator;
    private java.awt.Label lblResultLabel;
    // End of variables declaration//GEN-END:variables
}
